[package]
name = "snow_read"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quick-xml = "0.27.1"
roxmltree = "0.17.0"
serde = { version = "1.0.152", features = ["derive", "std"] }
serde-deserialize-over = "0.1.1"
serde-xml-rs = "0.6.0"
serde_with = "2.1.0"
