# rustfmt.toml
## web description of options: https://rust-lang.github.io/rustfmt/?version=v1.6.0&search=

# required_version   # specify rustfmt version requirement
# ignore = []        # files for rustfmt to ignore

## meta-config
style_edition = "2024"
unstable_features = true


## general spacing
max_width = 120
tab_spaces = 8  # legible groups! :)

## import organization
imports_granularity = "Crate"      # group all imports for a crate together
group_imports = "StdExternalCrate" # category style grouping of imports (ala isort in python)
imports_indent = "Visual"

## struct/enum related
struct_field_align_threshold = 40 # move distance to seek type alignment in struct fields
enum_discrim_align_threshold = 40 # move distance to seek type alignment in enum discriminants
use_field_init_shorthand = true   # let _ = some_struct {x, y, z}

## impl organization
reorder_impl_items = true # assoc_type & const at top of impl
